config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :models
  match '/shop',    to: 'static_pages#shop',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/add_car', to: 'static_pages#add_car', via: 'get'
  match '/profile_info', to: 'static_pages#profile_info', via: 'get'
  

 root 'static_pages#home'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts    
  has_many :photos
  has_many :postcomments  
  has_many :votes 

  validates :nickname, presence: true 
  validates :nickname, length: { in: 3..12 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

protect_from_forgery with: :exception


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def shop
  end

  def contact
  end

  def about
  end

  def add_car
  end

  def profile_info
  end
  	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
Car Sales Site by <strong>Valentin Tokar</strong>
</small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
     
      <%= link_to "Car Sale", root_path , id: "logo" %>
      
      <nav>
         <div class = "center">
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>  
           <li><%= link_to "Shop", shop_path %></li>
      <ul class="nav pull-right">
              <ul class="nav nav-pills">
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Menu<b class="caret"></b></a>
        <ul id="menu1" class="dropdown-menu">
          <li><%= link_to "Add car", add_car_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Profile info", profile_info_path %></li>
        </ul>
      </li>
    </ul>



<ul class="nav pull-right">
              <ul class="nav nav-pills">
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Authentication<b class="caret"></b></a>
        <ul id="menu1" class="dropdown-menu">
 <% if current_model.nil? %>
    <li>
    <%= link_to model_session_path do %>
      <i class="glyphicon glyphicon-user"></i> Login
      <%end%>
      </li>
      <% else %> 
      <li>
      <%= link_to destroy_model_session_path, method: :delete do %>
      <i class="glyphicon glyphicon-log-in"></i> Logout
  <%end%>
      </li>
       <% end %>
          <li class="divider"></li>
         <li> <%= link_to "Sign up now!", new_model_registration_path %></li>
        </ul>
      </li>
    </ul>
     </ul>







         </div>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Car Sales</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>
  Here will be some information about our company
</p>

app/views/static_pages/add_car.html.erb
<% provide(:title, 'Add_car') %>
<h1>Car garage</h1>
<p>
  Here you will be able to add your car for sale
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Here will be our contacts
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome , Dude !</h1>

  <h2>
    Here you can easilly sell or buy a car !
  </h2>
  <%= image_tag("logo.png", alt: "Logo") %>
</div>

app/views/static_pages/profile_info.html.erb
<% provide(:title, 'Profile_info') %>
<h1>Profile info</h1>
<p>
  Here will be your profile info
</p>

app/views/static_pages/shop.html.erb
<h1>Choose the car of your dream !</h1>
<p>Will be able soon</p>